### ISSUE TITLE
heap-buffer-overflow in simann.c

### ISSUE THREAD

**Issue by dschopf** [potfit/potfit#30]
a6bdc5e4971798adc6f1dd3f6f417cd4ec974b64 introduced a heap-buffer-overflow which apparently nobody noticed because it did not cause a crash. Only after the rework the memory layout seems to have changed and now this causes a segfault.

The problem is in the `store_pot_data` function, which is only used for tabulated potentials.
There the for loop implicitly assumes that g_pot.opt_pot.begin contains entries for (m)eam potentials.

We should investigate if this function is really needed for any potential other than meam.

```
=================================================================
==32393==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000001c0 at pc 0x00000053e1ca bp 0x7ffeadabd9e0 sp 0x7ffeadabd9d8
READ of size 8 at 0x6020000001c0 thread T0
    #0 0x53e1c9 in store_pot_data ./potfit-dschopf/build/../src/simann.c:223:26
    #1 0x53f76d in run_simulated_annealing ./potfit-dschopf/build/../src/simann.c:329:3
    #2 0x525b13 in run_optimization ./potfit-dschopf/build/../src/optimize.c:47:3
    #3 0x50e36d in main ./potfit-dschopf/build/../src/potfit.c:130:7
    #4 0x7f241739c449 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.25-r7/work/glibc-2.25/csu/../csu/libc-start.c:295
    #5 0x419f79 in _start (./potfit-dschopf/bin/potfit_tab_pair_mkl_asan_debug+0x419f79)

0x6020000001c0 is located 8 bytes to the right of 8-byte region [0x6020000001b0,0x6020000001b8)
allocated by thread T0 here:
    #0 0x4d6d70 in __interceptor_malloc (./potfit-dschopf/bin/potfit_tab_pair_mkl_asan_debug+0x4d6d70)
    #1 0x524725 in Malloc ./potfit-dschopf/build/../src/memory.c:66:13
    #2 0x529939 in allocate_memory_for_potentials ./potfit-dschopf/build/../src/potential_input.c:386:24
    #3 0x527cf1 in read_pot_table ./potfit-dschopf/build/../src/potential_input.c:125:3
    #4 0x50ee27 in read_input_files ./potfit-dschopf/build/../src/potfit.c:234:5
    #5 0x50de57 in main ./potfit-dschopf/build/../src/potfit.c:78:3
    #6 0x7f241739c449 in __libc_start_main /var/tmp/portage/sys-libs/glibc-2.25-r7/work/glibc-2.25/csu/../csu/libc-start.c:295

SUMMARY: AddressSanitizer: heap-buffer-overflow ./potfit-dschopf/build/../src/simann.c:223:26 in store_pot_data
Shadow bytes around the buggy address:
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa 05 fa fa fa fd fa fa fa 00 05 fa fa fd fd
  0x0c047fff8010: fa fa 00 06 fa fa 00 02 fa fa 00 02 fa fa 00 03
  0x0c047fff8020: fa fa 05 fa fa fa 06 fa fa fa 04 fa fa fa 04 fa
=>0x0c047fff8030: fa fa 04 fa fa fa 00 fa[fa]fa 00 fa fa fa 00 fa
  0x0c047fff8040: fa fa 00 fa fa fa 04 fa fa fa 04 fa fa fa 00 fa
  0x0c047fff8050: fa fa 00 fa fa fa 00 fa fa fa 05 fa fa fa 00 fa
  0x0c047fff8060: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047fff8070: fa fa fd fa fa fa fd fa fa fa fd fd fa fa 04 fa
  0x0c047fff8080: fa fa 00 00 fa fa 00 00 fa fa 00 00 fa fa 00 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32393==ABORTING
```

**Comment by dschopf** [comment]
Should be fixed with 96b9b99-
