### ISSUE TITLE
Default compliler option "-march=native" does not work with current clang compiler

### ISSUE THREAD

**Issue by p-bro** [potfit/potfit#98]
"-march=native", a default compiler option for gcc and clang, set in line 407 of wscript, does not work with current versions of clang on Mac OS 12.4 running on M1 (arm), the build phase fails with the error:
```
[ 8/28] Compiling src/potential_output.c
clang: error: the clang compiler does not support '-march=native'
```

(interestingly, the first 7 files compile without issues).

Removing this default option allows the build to succeed. Build settings:
```
Checking for 'icc' (C compiler)          : not found 
Checking for 'clang' (C compiler)        : /opt/local/bin/clang 
Checking for header Accelerate/Accelerate.h : yes 

potfit has been configured with the following options:
potential model      = tab
interaction          = eam
math library         = acc
options              = stress
```

Tested clang versions:
```
clang version 14.0.5
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-14/bin

Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dschopf** [comment]
Apparently this will be added in clang-15 https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-march-native-M1
I will check how this can be fixed for older compilers.

**Comment by p-bro** [comment]
```
$ ./waf configure -i eam -m tab --enable-stress --enable-resc
Setting top to                           : /Users/phslay/Code/potfit 
Setting out to                           : /Users/phslay/Code/potfit/build 
Checking for 'icc' (C compiler)          : not found 
Checking for 'clang' (C compiler)        : /opt/local/bin/clang 
Traceback (most recent call last):
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/phslay/Code/potfit/.waf3-2.0.19-8538b4ab53a7d24a478b70cb8d72b921/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/Users/phslay/Code/potfit/wscript", line 213, in configure
    _check_compiler_options(cnf)
  File "/Users/phslay/Code/potfit/wscript", line 408, in _check_compiler_options
    if _platform != "darwin" or cnf.env.CC_VERSION[0] > 14:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by p-bro** [comment]
That one works - thank you!
